// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type UserGetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserGetResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserGetResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserGetResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserGetListResponse struct {
	List                 []*UserGetResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserGetListResponse) Reset()         { *m = UserGetListResponse{} }
func (m *UserGetListResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetListResponse) ProtoMessage()    {}
func (*UserGetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserGetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetListResponse.Unmarshal(m, b)
}
func (m *UserGetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetListResponse.Marshal(b, m, deterministic)
}
func (m *UserGetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetListResponse.Merge(m, src)
}
func (m *UserGetListResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetListResponse.Size(m)
}
func (m *UserGetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetListResponse proto.InternalMessageInfo

func (m *UserGetListResponse) GetList() []*UserGetResponse {
	if m != nil {
		return m.List
	}
	return nil
}

type UserSetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSetRequest) Reset()         { *m = UserSetRequest{} }
func (m *UserSetRequest) String() string { return proto.CompactTextString(m) }
func (*UserSetRequest) ProtoMessage()    {}
func (*UserSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSetRequest.Unmarshal(m, b)
}
func (m *UserSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSetRequest.Marshal(b, m, deterministic)
}
func (m *UserSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSetRequest.Merge(m, src)
}
func (m *UserSetRequest) XXX_Size() int {
	return xxx_messageInfo_UserSetRequest.Size(m)
}
func (m *UserSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSetRequest proto.InternalMessageInfo

func (m *UserSetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserSetRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserSetRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserSetResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSetResponse) Reset()         { *m = UserSetResponse{} }
func (m *UserSetResponse) String() string { return proto.CompactTextString(m) }
func (*UserSetResponse) ProtoMessage()    {}
func (*UserSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSetResponse.Unmarshal(m, b)
}
func (m *UserSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSetResponse.Marshal(b, m, deterministic)
}
func (m *UserSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSetResponse.Merge(m, src)
}
func (m *UserSetResponse) XXX_Size() int {
	return xxx_messageInfo_UserSetResponse.Size(m)
}
func (m *UserSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSetResponse proto.InternalMessageInfo

func (m *UserSetResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "proto.EmptyRequest")
	proto.RegisterType((*UserGetRequest)(nil), "proto.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "proto.UserGetResponse")
	proto.RegisterType((*UserGetListResponse)(nil), "proto.UserGetListResponse")
	proto.RegisterType((*UserSetRequest)(nil), "proto.UserSetRequest")
	proto.RegisterType((*UserSetResponse)(nil), "proto.UserSetResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0x87, 0xb3, 0x40, 0x5b, 0x3b, 0x1a, 0x34, 0xdb, 0xd8, 0x6c, 0x38, 0x11, 0x4e, 0xe8, 0xa1,
	0x31, 0xd5, 0x53, 0x6f, 0x1e, 0x0c, 0x31, 0xf1, 0x60, 0xd8, 0xf8, 0x00, 0x28, 0xa3, 0x21, 0x29,
	0x7f, 0xdc, 0x59, 0x4c, 0x7c, 0x70, 0xef, 0xa6, 0x0b, 0xb5, 0x80, 0xf4, 0xc4, 0xee, 0xe4, 0x1b,
	0xe6, 0xfb, 0xcd, 0x02, 0xd4, 0x84, 0x6a, 0x55, 0xa9, 0x52, 0x97, 0x7c, 0x62, 0x3e, 0x81, 0x0b,
	0x67, 0x0f, 0x79, 0xa5, 0xbf, 0x63, 0xfc, 0xac, 0x91, 0x74, 0xe0, 0x83, 0xfb, 0x42, 0xa8, 0x22,
	0xd4, 0x6d, 0x85, 0xbb, 0x60, 0x65, 0xa9, 0x60, 0x3e, 0x0b, 0x27, 0xb1, 0x95, 0xa5, 0x41, 0x02,
	0xe7, 0x7f, 0x04, 0x55, 0x65, 0x41, 0x38, 0x44, 0x38, 0x07, 0xa7, 0x48, 0x72, 0x14, 0x96, 0xcf,
	0xc2, 0x79, 0x6c, 0xce, 0xfc, 0x02, 0xec, 0xe4, 0x03, 0x85, 0x6d, 0xa0, 0xdd, 0x91, 0x0b, 0x98,
	0x25, 0x69, 0xaa, 0x90, 0x48, 0x38, 0x06, 0xdc, 0x5f, 0x83, 0x7b, 0x58, 0xb4, 0x23, 0x9e, 0x32,
	0x3a, 0x8c, 0xb9, 0x06, 0x67, 0x9b, 0x91, 0x16, 0xcc, 0xb7, 0xc3, 0xd3, 0xf5, 0xb2, 0x09, 0xb2,
	0x1a, 0xc8, 0xc4, 0x86, 0x09, 0x9e, 0x9b, 0x1c, 0xf2, 0x90, 0x63, 0x2f, 0xc5, 0xfe, 0x4b, 0x59,
	0xa3, 0x52, 0x76, 0x5f, 0xea, 0xaa, 0xc9, 0x2d, 0x3b, 0xb9, 0x97, 0x30, 0x55, 0x48, 0xf5, 0x56,
	0x9b, 0x9f, 0x9e, 0xc4, 0xed, 0x6d, 0xfd, 0xc3, 0x1a, 0xf6, 0xb1, 0x78, 0x2f, 0x25, 0xaa, 0xaf,
	0xec, 0x0d, 0xf9, 0x1d, 0xd8, 0x11, 0x6a, 0x7e, 0x39, 0xb4, 0x36, 0x72, 0xde, 0x91, 0x30, 0x7c,
	0x03, 0xb3, 0x76, 0x0b, 0x7c, 0xd1, 0x22, 0xdd, 0xe7, 0xf2, 0xbc, 0x7e, 0x5f, 0x6f, 0x5d, 0x1b,
	0x98, 0x47, 0xa8, 0xa5, 0x56, 0x98, 0xe4, 0xe3, 0xdd, 0x47, 0xa6, 0xde, 0xb0, 0x9d, 0xad, 0x1c,
	0xd8, 0xca, 0x71, 0xdb, 0xce, 0x3e, 0x5e, 0xa7, 0xa6, 0x7c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x56, 0x74, 0xb5, 0x9f, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInfoServiceClient is the client API for UserInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInfoServiceClient interface {
	Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	GetList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserGetListResponse, error)
	GetStream(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (UserInfoService_GetStreamClient, error)
	Set(ctx context.Context, in *UserSetRequest, opts ...grpc.CallOption) (*UserSetResponse, error)
}

type userInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoServiceClient(cc *grpc.ClientConn) UserInfoServiceClient {
	return &userInfoServiceClient{cc}
}

func (c *userInfoServiceClient) Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserInfoService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoServiceClient) GetList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UserGetListResponse, error) {
	out := new(UserGetListResponse)
	err := c.cc.Invoke(ctx, "/proto.UserInfoService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoServiceClient) GetStream(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (UserInfoService_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserInfoService_serviceDesc.Streams[0], "/proto.UserInfoService/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userInfoServiceGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserInfoService_GetStreamClient interface {
	Recv() (*UserGetResponse, error)
	grpc.ClientStream
}

type userInfoServiceGetStreamClient struct {
	grpc.ClientStream
}

func (x *userInfoServiceGetStreamClient) Recv() (*UserGetResponse, error) {
	m := new(UserGetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userInfoServiceClient) Set(ctx context.Context, in *UserSetRequest, opts ...grpc.CallOption) (*UserSetResponse, error) {
	out := new(UserSetResponse)
	err := c.cc.Invoke(ctx, "/proto.UserInfoService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoServiceServer is the server API for UserInfoService service.
type UserInfoServiceServer interface {
	Get(context.Context, *UserGetRequest) (*UserGetResponse, error)
	GetList(context.Context, *EmptyRequest) (*UserGetListResponse, error)
	GetStream(*EmptyRequest, UserInfoService_GetStreamServer) error
	Set(context.Context, *UserSetRequest) (*UserSetResponse, error)
}

// UnimplementedUserInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserInfoServiceServer struct {
}

func (*UnimplementedUserInfoServiceServer) Get(ctx context.Context, req *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserInfoServiceServer) GetList(ctx context.Context, req *EmptyRequest) (*UserGetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedUserInfoServiceServer) GetStream(req *EmptyRequest, srv UserInfoService_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (*UnimplementedUserInfoServiceServer) Set(ctx context.Context, req *UserSetRequest) (*UserSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterUserInfoServiceServer(s *grpc.Server, srv UserInfoServiceServer) {
	s.RegisterService(&_UserInfoService_serviceDesc, srv)
}

func _UserInfoService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).Get(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfoService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).GetList(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfoService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserInfoServiceServer).GetStream(m, &userInfoServiceGetStreamServer{stream})
}

type UserInfoService_GetStreamServer interface {
	Send(*UserGetResponse) error
	grpc.ServerStream
}

type userInfoServiceGetStreamServer struct {
	grpc.ServerStream
}

func (x *userInfoServiceGetStreamServer) Send(m *UserGetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UserInfoService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).Set(ctx, req.(*UserSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserInfoService",
	HandlerType: (*UserInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserInfoService_Get_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _UserInfoService_GetList_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _UserInfoService_Set_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _UserInfoService_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}
